services:
  - type: web
    name: crud-laravel-docker
    runtime: docker
    repo: https://github.com/KianHmz/CRUD-Laravel
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /data/database.sqlite
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    startCommand: |
      cp .env.example .env
      php artisan key:generate
      php artisan migrate --force
      apache2-foreground
